In [1]:
import pandas as pd
import geopandas as gpd

In [8]:
df_yelp = pd.read_csv("../data/yelp_SD_parks.csv")
df_yelp

,name,address,phone,id,url,rating,review_count,longitude,latitude,is_closed
0,Balboa Park,"1549 El Prado San Diego, CA 92101",1.619239e+10,9M_FW_-Ipx93I36w-_ykBg,https://www.yelp.com/biz/balboa-park-san-diego...,5.0,2105,-117.153150,32.734502,False
1,Civita Park,"7960 Civita Blvd San Diego, CA 92108",NaN,3AEHjqNrTmggA6G9VdhQfg,https://www.yelp.com/biz/civita-park-san-diego...,4.5,46,-117.147278,32.778315,False
2,Waterfront Park,"1600 Pacific Hwy San Diego, CA 92101",1.619233e+10,3unbJeYrn1RmInZGmjp80g,https://www.yelp.com/biz/waterfront-park-san-d...,4.5,242,-117.172479,32.721952,False
3,Trolley Barn Park,"Adams Ave And Florida St San Diego, CA 92116",NaN,PvHxIYrmaiFKdWUDTMDzcg,https://www.yelp.com/biz/trolley-barn-park-san...,4.5,102,-117.143789,32.762463,False
4,Bay View Park,"413 1st St Coronado, CA 92118",NaN,6IF4VB9-fkv_F-LBvG8ppQ,https://www.yelp.com/biz/bay-view-park-coronad...,5.0,42,-117.178967,32.701785,False
...,...,...,...,...,...,...,...,...,...,...
828,Del Cerro - San Diego,"San Diego, CA 92120",1.619287e+10,ggbc59hSsl6pxCGSN1QLQA,https://www.yelp.com/biz/del-cerro-san-diego-s...,4.5,12,-117.073524,32.792626,False
829,San Diego Metropolitan Transit System,"1255 Imperial Ave Ste 1000 San Diego, CA 92101",1.619238e+10,c8jhIMcwSjWqBD7S-faKYg,https://www.yelp.com/biz/san-diego-metropolita...,2.5,268,-117.153400,32.705760,False
830,Petco Park,"100 Park Blvd San Diego, CA 92101",1.619796e+10,HkgSbRLVMRHExsRkImIK5A,https://www.yelp.com/biz/petco-park-san-diego?...,4.0,1667,-117.157054,32.707246,False
831,Ann D. L'Heureux Memorial Dog Park,"2700 Carlsbad Village Dr Carlsbad, CA 92008",1.760434e+10,wYGJ65iVMi74-3TylWxY0Q,https://www.yelp.com/biz/ann-d-l-heureux-memor...,3.0,50,-117.316419,33.171137,False
832,Fairbrook Farm,"4949 S Mission Rd Fallbrook, CA 92028",1.760729e+10,l3ZIY78OBs6BfkMQifY28g,https://www.yelp.com/biz/fairbrook-farm-fallbr...,5.0,1,-117.227747,33.302164,False

In [4]:
df_y

,Unnamed: 0,address_number_primary,address_dir_primary,address_road_primary,address_sfx_primary,address,loc,point,latitude,longtitude
0,0,5600,NaN,MISSION CENTER,RD,"5600 MISSION CENTER RD, San Diego, CA, USA","Mission Center Road, Birdland, Linda Vista, Sa...","(32.789371, -117.150177, 0.0)",32.789371,-117.150177
1,1,2100,NaN,PARK,BLV,"2100 PARK BLV, San Diego, CA, USA","Park Blvd, San Diego, San Diego County, Califo...","(32.7047646, -117.157846, 0.0)",32.704765,-117.157846
2,2,2100,NaN,K,ST,"2100 K ST, San Diego, CA, USA","K Street, Gaslamp Quarter, San Diego, San Dieg...","(32.7083258, -117.1604615, 0.0)",32.708326,-117.160461
3,3,1100,NaN,27TH (SB),ST,"1100 27TH (SB) ST, San Diego, CA, USA","27th (Sb) Street, Chula Vista, San Diego Count...","(32.592018, -117.075363, 0.0)",32.592018,-117.075363
4,4,300,NaN,47TH,ST,"300 47TH ST, San Diego, CA, USA","47th Street, Chollas View, San Diego, San Dieg...","(32.7117026, -117.0935445, 0.0)",32.711703,-117.093545
...,...,...,...,...,...,...,...,...,...,...
7601,7601,2100,NaN,VALENTINO,ST,"2100 VALENTINO ST, San Diego, CA, USA","Valentino Street, San Diego, San Diego County,...","(32.558376, -117.067169, 0.0)",32.558376,-117.067169
7602,7602,3200,NaN,TENNYSON,ST,"3200 TENNYSON ST, San Diego, CA, USA","Tennyson Street, Ocean Beach, San Diego, San D...","(32.7413287, -117.2346468, 0.0)",32.741329,-117.234647
7603,7603,0,NaN,EL CAMINO REAL,NaN,"0 EL CAMINO REAL, San Diego, CA, USA","San Diego, San Diego County, California, Unite...","(32.7174202, -117.1627728, 0.0)",32.717420,-117.162773
7604,7604,8900,NaN,GENESEE,AV,"8900 GENESEE AV, San Diego, CA, USA","Genesee Avenue, Torrey Pines, San Diego, San D...","(32.8903071, -117.2356658, 0.0)",32.890307,-117.235666
7605,7605,5100,NaN,EWING,ST,"5100 EWING ST, San Diego, CA, USA","Ewing Street, Montezuma Mesa, Del Cerro, San D...","(32.771488, -117.061562, 0.0)",32.771488,-117.061562

In [6]:
a = pd.concat([df_yelp, df_y])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [7]:
a

,Unnamed: 0,Unnamed: 0.1,address,address_dir_primary,address_number_primary,address_road_primary,address_sfx_primary,geometry,latitude,loc,longitude,longtitude,point
0,1,1.0,"5000 UNIVERSITY AVE, San Diego, CA, USA",NaN,5000,UNIVERSITY,AVE,POINT (-117.1186691 32.7497606),32.749761,"University Avenue, Cherokee Point, Normal Heig...",-117.118669,NaN,"(32.7497606, -117.1186691, 0.0)"
1,2,2.0,"800 SAWTELLE AVE, San Diego, CA, USA",NaN,800,SAWTELLE,AVE,POINT (-117.0269166 32.71171769999999),32.711718,"Sawtelle Avenue, Lomita, San Diego, San Diego ...",-117.026917,NaN,"(32.7117177, -117.0269166, 0.0)"
2,3,3.0,"5000 UNIVERSITY AVE, San Diego, CA, USA",NaN,5000,UNIVERSITY,AVE,POINT (-117.1186691 32.7497606),32.749761,"University Avenue, Cherokee Point, Normal Heig...",-117.118669,NaN,"(32.7497606, -117.1186691, 0.0)"
3,4,4.0,"5200 CLAIREMONT MESA BLV, San Diego, CA, USA",NaN,5200,CLAIREMONT MESA,BLV,POINT (-117.1194774 32.8335646),32.833565,"Clairemont Mesa Boulevard, San Diego, San Dieg...",-117.119477,NaN,"(32.8335646, -117.1194774, 0.0)"
4,6,6.0,"4300 MANZANITA DR, San Diego, CA, USA",NaN,4300,MANZANITA,DR,POINT (-117.105569 32.73629099999999),32.736291,"Manzanita Drive, Fox Canyon, City Heights, San...",-117.105569,NaN,"(32.736291, -117.105569, 0.0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7601,7601,NaN,"2100 VALENTINO ST, San Diego, CA, USA",NaN,2100,VALENTINO,ST,NaN,32.558376,"Valentino Street, San Diego, San Diego County,...",NaN,-117.067169,"(32.558376, -117.067169, 0.0)"
7602,7602,NaN,"3200 TENNYSON ST, San Diego, CA, USA",NaN,3200,TENNYSON,ST,NaN,32.741329,"Tennyson Street, Ocean Beach, San Diego, San D...",NaN,-117.234647,"(32.7413287, -117.2346468, 0.0)"
7603,7603,NaN,"0 EL CAMINO REAL, San Diego, CA, USA",NaN,0,EL CAMINO REAL,NaN,NaN,32.717420,"San Diego, San Diego County, California, Unite...",NaN,-117.162773,"(32.7174202, -117.1627728, 0.0)"
7604,7604,NaN,"8900 GENESEE AV, San Diego, CA, USA",NaN,8900,GENESEE,AV,NaN,32.890307,"Genesee Avenue, Torrey Pines, San Diego, San D...",NaN,-117.235666,"(32.8903071, -117.2356658, 0.0)"
7605,7605,NaN,"5100 EWING ST, San Diego, CA, USA",NaN,5100,EWING,ST,NaN,32.771488,"Ewing Street, Montezuma Mesa, Del Cerro, San D...",NaN,-117.061562,"(32.771488, -117.061562, 0.0)"